"""initial schema

Revision ID: 9d0a2638b416
Revises: 
Create Date: 2026-09-23 18:16:36.014891

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '9d0a2638b416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_tj', sa.String(length=200), nullable=False),
    sa.Column('description_ru', sa.String(length=500), nullable=True),
    sa.Column('description_tj', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_tj', sa.String(length=200), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('description_tj', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.Enum('tj', 'ru', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('theme', sa.Enum('system', 'light', 'dark', name='thememode', native_enum=False, length=32), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('active_role', sa.Enum('abiturient', 'schoolboy', name='userrole', native_enum=False, length=32), nullable=True),
    sa.Column('admin_role', sa.Enum('content_manager', 'superadmin', name='adminrole', native_enum=False, length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('abiturient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('backup_cluster_id', sa.Integer(), nullable=True),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['backup_cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('abiturient_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_abiturient_profiles_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abiturient_profiles_region'), ['region'], unique=False)

    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('exam_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('tj', 'ru', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_tests_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_tests_year'), ['year'], unique=False)

    op.create_table('school_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('language_of_study', sa.Enum('tj', 'ru', name='language', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('school_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_profiles_grade'), ['grade'], unique=False)

    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_tj', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_grade'), ['grade'], unique=False)

    op.create_table('test_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('abiturient', 'schoolboy', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('test_type', sa.Enum('topic_test', 'section_test', 'practice', 'exam_test', 'lesson_check', 'mistakes', name='testtype', native_enum=False, length=32), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'finished', name='attemptstatus', native_enum=False, length=32), nullable=False),
    sa.Column('is_timed', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_streak', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('mmt_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_user_type_ref', ['user_id', 'test_type', 'reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('abiturient', 'schoolboy', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('abiturient', 'schoolboy', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('correct_answer', 'streak_bonus', 'achievement', 'test_completion', name='pointsreason', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_ledger_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_points_role_created', ['role', 'created_at'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('parent_topic_id', sa.Integer(), nullable=True),
    sa.Column('title_ru', sa.String(length=300), nullable=False),
    sa.Column('title_tj', sa.String(length=300), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_parent_topic_id'), ['parent_topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_subject_id'), ['subject_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('tj', 'ru', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_topic_id'), ['topic_id'], unique=False)

    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('abiturient', 'schoolboy', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', 'role', name='uq_lesson_progress')
    )
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_progress_user_id'), ['user_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('exam_test_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.Enum('tj', 'ru', name='language', native_enum=False, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False, length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['exam_test_id'], ['exam_tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_exam_test_id'), ['exam_test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)

    op.create_table('marked_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_marked_user_question')
    )
    with op.batch_alter_table('marked_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marked_questions_user_id'), ['user_id'], unique=False)

    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answer_attempt_question')
    )
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_user_answers_attempt_id'))

    op.drop_table('user_answers')
    with op.batch_alter_table('marked_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marked_questions_user_id'))

    op.drop_table('marked_questions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_questions_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_questions_language'))
        batch_op.drop_index(batch_op.f('ix_questions_exam_test_id'))

    op.drop_table('questions')
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_progress_user_id'))

    op.drop_table('lesson_progress')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_topic_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_language'))

    op.drop_table('lessons')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_subject_id'))
        batch_op.drop_index(batch_op.f('ix_topics_parent_topic_id'))

    op.drop_table('topics')
    with op.batch_alter_table('points_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_points_role_created')
        batch_op.drop_index(batch_op.f('ix_points_ledger_user_id'))

    op.drop_table('points_ledger')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_attempts_user_id'))
        batch_op.drop_index('ix_attempt_user_type_ref')

    op.drop_table('test_attempts')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_grade'))
        batch_op.drop_index(batch_op.f('ix_subjects_cluster_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('school_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_profiles_grade'))

    op.drop_table('school_profiles')
    with op.batch_alter_table('exam_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_tests_year'))
        batch_op.drop_index(batch_op.f('ix_exam_tests_cluster_id'))

    op.drop_table('exam_tests')
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_tokens_user_id'))

    op.drop_table('device_tokens')
    with op.batch_alter_table('abiturient_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abiturient_profiles_region'))
        batch_op.drop_index(batch_op.f('ix_abiturient_profiles_cluster_id'))

    op.drop_table('abiturient_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('clusters')
    op.drop_table('achievements')
    # ### end Alembic commands ###
