"""offline sync client id

Revision ID: 4d6e965c66ba
Revises: 00257020fe05
Create Date: 2026-09-24 18:31:46.443979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6e965c66ba'
down_revision = '00257020fe05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_attempt_user_client', ['user_id', 'client_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attempt_user_client', type_='unique')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
